### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by ghost** [yescallop/EssentialsNK#20]
android@localhost:/EssentialsNK$ mvn install
[INFO] Scanning for projects...
[INFO]                                                             
[INFO] ------------------------------------------------------------------------
[INFO] Building EssentialsNK 1.0.8
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ EssentialsNK ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ EssentialsNK ---
[INFO] Compiling 54 source files to /home/android/EssentialsNK/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.771s
[INFO] Finished at: Wed Jun 28 05:50:04 KST 2017
[INFO] Final Memory: 9M/27M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project EssentialsNK: Compilation failure: Compilation failure:
[ERROR] /home/android/EssentialsNK/src/main/java/cn/yescallop/essentialsnk/command/defaults/CompassCommand.java:[28,17] error: an enum switch case label must be the unqualified name of an enumeration constant
[ERROR]
[ERROR] /home/android/EssentialsNK/src/main/java/cn/yescallop/essentialsnk/command/defaults/CompassCommand.java:[31,17] error: an enum switch case label must be the unqualified name of an enumeration constant
[ERROR]
[ERROR] /home/android/EssentialsNK/src/main/java/cn/yescallop/essentialsnk/command/defaults/CompassCommand.java:[31,12] error: duplicate case label
[ERROR]
[ERROR] /home/android/EssentialsNK/src/main/java/cn/yescallop/essentialsnk/command/defaults/CompassCommand.java:[34,17] error: an enum switch case label must be the unqualified name of an enumeration constant
[ERROR]
[ERROR] /home/android/EssentialsNK/src/main/java/cn/yescallop/essentialsnk/command/defaults/CompassCommand.java:[34,12] error: duplicate case label
[ERROR]
[ERROR] /home/android/EssentialsNK/src/main/java/cn/yescallop/essentialsnk/command/defaults/CompassCommand.java:[37,17] error: an enum switch case label must be the unqualified name of an enumeration constant
[ERROR]
[ERROR] /home/android/EssentialsNK/src/main/java/cn/yescallop/essentialsnk/command/defaults/CompassCommand.java:[37,12] error: duplicate case label
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
android@localhost:~/EssentialsNK$

**Comment by yescallop** [comment]
Cannot reproduce, check out the latest version and retry
